Update readme
Nantes-training/dnf-202401-common pull request #11
Opened 2024-02-15 10:49 UTC by AlexisCompain

2024-02-15 10:50 UTC, vlandema commented on README.md
> +Mon ajout de texte
English please 🕵️

2024-02-15 10:51 UTC, vlandema requested changes
Nope

2024-02-15 10:51 UTC, vlandema commented on README.md
> +Mon ajout de texte
English please 🕵️

2024-02-15 10:56 UTC, AlexisCompain commented on README.md
> +Mon ajout de texte
c'est pas faux

2024-02-15 10:57 UTC, vlandema commented on README.md
> +Mon ajout de texte
```suggestion
Yes this in in english
```

2024-02-15 10:58 UTC, vlandema commented on README.md
> +- You can have superpower that helps you install more appliances and quicked etc...
```suggestion
- You can have hyperpower that helps you install more appliances and quicked etc...
```

2024-02-29 11:08 UTC, vlandema approved these changes

2024-02-29 11:09 UTC, merged

2024-02-29 11:09 UTC, vlandema commented
GG